export const types = {
    GET_PRODUCTS: '[Product] GET_PRODUCTS',
    GET_PRODUCTS_TOTAL:'[Product] GET_PRODUCTS_TOTAL',
    GET_PRODUCTS_CATEGORY: '[Product] GET_PRODUCTS_CATEGORY',
    GET_PRODUCT: '[Product] GET_PRODUCT',
    ADD_PRODUCT_CART: '[Product] ADD_PRODUCT_CART',
    UPDATE_PRODUCT_CART: '[Product] UPDATE_PRODUCT_CART',
    DELETE_PRODUCT_CART: '[Product] DELETE_PRODUCT_CART',
    EMPTY_CART: '[Product] EMPTY_CART'

}