export const types = {
    GET_PRODUCTS: '[Product] GET_PRODUCTS',
    GET_PRODUCTS_TOTAL:'[Product] GET_PRODUCTS_TOTAL',
    GET_PRODUCTS_CATEGORY: '[Product] GET_PRODUCTS_CATEGORY',
    GET_PRODUCT: '[Product] GET_PRODUCT',
    ADD_PRODUCT_CAR: '[Product] ADD_PRODUCT',
    DELETE_PRODUCT_CAR: '[Product] DELETE_PRODUCT',
    EMPTY_CAR: '[Product] EMPTY_CAR'

}